CREATE TABLE CRUD_PECAS(

ID_PECA INT IDENTITY(1,1)NOT NULL
,NOME VARCHAR(100)
,CODIGOPECA VARCHAR (100)
,CODIGODEBARRAS VARCHAR (100)
,MARCA VARCHAR (100)
,DISTRIBUIDOR VARCHAR (100)
,PRECO VARCHAR (100)

CONSTRAINT PK_ID_PECA PRIMARY KEY (ID_PECA)
);